[package]
name = "filepath"
version = "0.1.0"
authors = ["Tom Schuster <evilpies@gmail.com>"]
categories = ["filesystem"]
keywords = ["path", "file"]

[target.'cfg(target_os="macos")'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["std", "fileapi"] }